### ISSUE TITLE
Add a disabled prop

### ISSUE THREAD

**Issue by arfeo** [STRML/react-resizable#86]
`Feature Request`

That would be great if the component had a special `disabled` prop. As for now, to disable `resizable` without rerendering parent component, one should use smth like this:

```css
.react-resizable-handle {
  display: none;
}
```

Thanks.
